In [1]:
#Import libraries
import pandas as pd
import nltk
import re

In [2]:
nltk.download('stopwords')
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\ashna\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [3]:
ps=PorterStemmer()

In [4]:
data=[]

In [5]:
#Read the Dataset
df=pd.read_csv('IMDB Dataset.csv')

In [6]:
df

review sentiment
0      One of the other reviewers has mentioned that ...  positive
1      A wonderful little production. <br /><br />The...  positive
2      I thought this was a wonderful way to spend ti...  positive
3      Basically there's a family where a little boy ...  negative
4      Petter Mattei's "Love in the Time of Money" is...  positive
...                                                  ...       ...
49995  I thought this movie did a down right good job...  positive
49996  Bad plot, bad dialogue, bad acting, idiotic di...  negative
49997  I am a Catholic taught in parochial elementary...  negative
49998  I'm going to have to disagree with the previou...  negative
49999  No one expects the Star Trek movies to be high...  negative

[50000 rows x 2 columns]

In [7]:
#Text Preprocessing

for i in range(0,1000):
  review=df['review'][i]

  #remove uneccessary things
  review=re.sub('[^a-zA-Z]',' ',review )

  #Lower case text
  review=review.lower()

  #split the text
  review=review.split()

  #Stemming & Remove Stopwords
  review=[ps.stem(word) for word in review if not word in 
          set(stopwords.words('english'))]

  review=' '.join(review)
  data.append(review)

In [8]:
#Tokenization or Vectorization
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer(max_features=3000)

In [9]:
cv

CountVectorizer(max_features=3000)

In [10]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

In [11]:
#Splitting the data into x & y

x=cv.fit_transform(data).toarray()
y=df.iloc[:1000,1:2].values

ct=ColumnTransformer([("one", OneHotEncoder(), [0])], remainder="passthrough")
y=ct.fit_transform(y)

In [12]:
print(x.shape)
print(y.shape)

(1000, 3000)
(1000, 2)


In [13]:
import numpy as np

In [14]:
x=np.asarray(x).astype(np.float32)
print(x)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 3. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [15]:
y=y[:,1:2]
y = np.asarray(y).astype(np.float32)
print(y)

[[1.]
 [1.]
 [1.]
 [0.]
 [1.]
 [1.]
 [1.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [1.]
 [0.]
 [1.]
 [0.]
 [1.]
 [0.]
 [1.]
 [0.]
 [0.]
 [1.]
 [1.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [1.]
 [1.]
 [0.]
 [0.]
 [1.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [0.]
 [1.]
 [1.]
 [0.]
 [0.]
 [1.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [1.]
 [1.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [0.]
 [1.]
 [1.]
 [0.]
 [1.]
 [1.]
 [0.]
 [1.]
 [1.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [1.]
 [1.]
 [1.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [1.]
 [1.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [1.

In [16]:
#Split the  data into train & test

from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

In [17]:
import tensorflow
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [18]:
model=Sequential()

In [19]:
model.add(Dense(1565,activation='relu'))
model.add(Dense(3000,activation='relu'))
model.add(Dense(1,activation='sigmoid'))
model.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])
model.fit(x_train,y_train,epochs=10)

Epoch 1/10
25/25 [==============================] - 1s 48ms/step - loss: 0.6246 - accuracy: 0.6875
Epoch 2/10
25/25 [==============================] - 1s 48ms/step - loss: 0.0610 - accuracy: 0.9875
Epoch 3/10
25/25 [==============================] - 1s 48ms/step - loss: 0.0017 - accuracy: 1.0000
Epoch 4/10
25/25 [==============================] - 1s 56ms/step - loss: 4.6405e-04 - accuracy: 1.0000
Epoch 5/10
25/25 [==============================] - 1s 53ms/step - loss: 3.0456e-04 - accuracy: 1.0000
Epoch 6/10
25/25 [==============================] - 1s 50ms/step - loss: 2.1960e-04 - accuracy: 1.0000
Epoch 7/10
25/25 [==============================] - 1s 52ms/step - loss: 1.7264e-04 - accuracy: 1.0000
Epoch 8/10
25/25 [==============================] - 1s 52ms/step - loss: 1.3644e-04 - accuracy: 1.0000
Epoch 9/10
25/25 [==============================] - 1s 51ms/step - loss: 1.1160e-04 - accuracy: 1.0000
Epoch 10/10
25/25 [==============================] - 1s 48ms/step - loss: 9.2796e-05 

In [20]:
#save the model
model.save('movie_review.h5')

In [21]:
text= "i love the movies"
text=re.sub('[^a-zA-Z]',' ',text)
text=text.lower()
text=text.split()
text=[ps.stem(word) for word in text if not word in set(stopwords.words('english'))]
text=' '.join(text)

In [22]:
y_p1= model.predict(cv.transform([text]))
y_p1=y_p1>0.5
y_p1

array([[ True]])

In [23]:
text

'love movi'