In [1]:
from tensorflow.keras.models import load_model
from tensorflow.keras.preprocessing import image

In [2]:
model = load_model("items.h5")

In [3]:
img = image.load_img("scissor.jpg",target_size = (64,64)) #testing for scissor

In [4]:
type(img)

PIL.Image.Image

In [5]:
x = image.img_to_array(img)
type(x)

numpy.ndarray

In [6]:
x.shape

(64, 64, 3)

In [7]:
import numpy as np
x = np.expand_dims(x,axis = 0)

In [8]:
x.shape

(1, 64, 64, 3)

In [9]:
pred = model.predict(x)

In [10]:
pred[0]

array([0., 0., 1.], dtype=float32)

In [11]:
index = ["paper","rock","scissors"]
prediction = index[np.argmax(pred[0])]
prediction

'scissors'

In [12]:
# testing for rock
img = image.load_img("rock.jpg",target_size = (64,64))
x = image.img_to_array(img)
x = np.expand_dims(x,axis =0)
pred = model.predict(x)
print(pred)
prediction = index[np.argmax(pred[0])]
prediction

[[0. 1. 0.]]


'rock'

In [13]:
# testing for paper
img = image.load_img("paper.jpg",target_size = (64,64))
x = image.img_to_array(img)
x = np.expand_dims(x,axis =0)
pred = model.predict(x)
print(pred)
prediction = index[np.argmax(pred[0])]
prediction

[[1. 0. 0.]]


'paper'