In [1]:
#import libraries
import numpy as np
import pandas as pd

In [8]:
dataset=pd.read_csv(r"D:\myproject\fruit_colors.csv")

In [9]:
dataset.head(11)

fruit_label fruit_name fruit_subtype  mass  width  height  color_score
0             1      apple  granny_smith   192    8.4     7.3         0.55
1             1      apple  granny_smith   180    8.0     6.8         0.59
2             1      apple  granny_smith   176    7.4     7.2         0.60
3             2   mandarin      mandarin    86    6.2     4.7         0.80
4             2   mandarin      mandarin    84    6.0     4.6         0.79
5             2   mandarin      mandarin    80    5.8     4.3         0.77
6             2   mandarin      mandarin    80    5.9     4.3         0.81
7             2   mandarin      mandarin    76    5.8     4.0         0.81
8             1      apple      braeburn   178    7.1     7.8         0.92
9             1      apple      braeburn   172    7.4     7.0         0.89
10            1      apple      braeburn   166    6.9     7.3         0.93

In [10]:
dataset.isnull().any()

fruit_label      False
fruit_name       False
fruit_subtype    False
mass             False
width            False
height           False
color_score      False
dtype: bool

In [30]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 59 entries, 0 to 58
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   fruit_label    59 non-null     int64  
 1   fruit_name     59 non-null     object 
 2   fruit_subtype  59 non-null     object 
 3   mass           59 non-null     int64  
 4   width          59 non-null     float64
 5   height         59 non-null     float64
 6   color_score    59 non-null     float64
dtypes: float64(3), int64(2), object(2)
memory usage: 3.4+ KB


In [13]:
i= dataset.iloc[:,0:7].values
o= dataset.iloc[:,7:].values

In [14]:
i

array([[1, 'apple', 'granny_smith', 192, 8.4, 7.3, 0.55],
       [1, 'apple', 'granny_smith', 180, 8.0, 6.8, 0.59],
       [1, 'apple', 'granny_smith', 176, 7.4, 7.2, 0.6],
       [2, 'mandarin', 'mandarin', 86, 6.2, 4.7, 0.8],
       [2, 'mandarin', 'mandarin', 84, 6.0, 4.6, 0.79],
       [2, 'mandarin', 'mandarin', 80, 5.8, 4.3, 0.77],
       [2, 'mandarin', 'mandarin', 80, 5.9, 4.3, 0.81],
       [2, 'mandarin', 'mandarin', 76, 5.8, 4.0, 0.81],
       [1, 'apple', 'braeburn', 178, 7.1, 7.8, 0.92],
       [1, 'apple', 'braeburn', 172, 7.4, 7.0, 0.89],
       [1, 'apple', 'braeburn', 166, 6.9, 7.3, 0.93],
       [1, 'apple', 'braeburn', 172, 7.1, 7.6, 0.92],
       [1, 'apple', 'braeburn', 154, 7.0, 7.1, 0.88],
       [1, 'apple', 'golden_delicious', 164, 7.3, 7.7, 0.7],
       [1, 'apple', 'golden_delicious', 152, 7.6, 7.3, 0.69],
       [1, 'apple', 'golden_delicious', 156, 7.7, 7.1, 0.69],
       [1, 'apple', 'golden_delicious', 156, 7.6, 7.5, 0.67],
       [1, 'apple', 'golden_del

In [15]:
o

array([], shape=(59, 0), dtype=float64)

In [16]:
i.shape

(59, 7)

In [17]:
o.shape

(59, 0)

In [19]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

In [22]:
ct = ColumnTransformer([("one",OneHotEncoder(),[1,2])],remainder = "passthrough")
i = ct.fit_transform(i)

In [23]:
from sklearn.model_selection import train_test_split
i_train,i_test,o_train,o_test = train_test_split(i,o,test_size = 0.2,random_state = 0)

In [24]:
print(i.shape,"input shape")
print(o.shape,"output shape")
print(i_train.shape,"input_train shape")
print(i_test.shape,"input_test shape")
print(o_train.shape,"output_train shape")
print(o_test.shape,"output_test shape")

(59, 19) input shape
(59, 0) output shape
(47, 19) input_train shape
(12, 19) input_test shape
(47, 0) output_train shape
(12, 0) output_test shape


In [25]:
i_train.shape

(47, 19)

In [26]:
o_train.shape

(47, 0)

In [28]:
from sklearn.preprocessing import StandardScaler
s = StandardScaler()
i_train = s.fit_transform(i_train)
i_test = s.fit_transform(i_test)

In [29]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
regression = Sequential()

In [31]:
regression.add(Dense(units=7, kernel_initializer="random_uniform", activation="relu"))

In [32]:
regression.add(Dense(units=12, kernel_initializer = "random_uniform", activation="relu")) #hidden layer

In [33]:
regression.add(Dense(units=12, kernel_initializer = "random_uniform", activation="relu")) #hidden layer

In [34]:
regression.add(Dense(units=12, kernel_initializer = "random_uniform", activation="relu")) #hidden layer

In [35]:
regression.add(Dense(units=1, kernel_initializer = "random_uniform", activation="relu"))

In [36]:
regression.compile(optimizer="rmsprop", loss="mse" ,metrics=["mse"])

In [37]:
regression.fit(i_train, o_train, epochs = 50)

Epoch 1/50
2/2 [==============================] - 1s 18ms/step - loss: nan - mse: nan
Epoch 2/50
2/2 [==============================] - 0s 6ms/step - loss: nan - mse: nan
Epoch 3/50
2/2 [==============================] - 0s 7ms/step - loss: nan - mse: nan
Epoch 4/50
2/2 [==============================] - 0s 5ms/step - loss: nan - mse: nan
Epoch 5/50
2/2 [==============================] - 0s 6ms/step - loss: nan - mse: nan
Epoch 6/50
2/2 [==============================] - 0s 6ms/step - loss: nan - mse: nan
Epoch 7/50
2/2 [==============================] - 0s 7ms/step - loss: nan - mse: nan
Epoch 8/50
2/2 [==============================] - 0s 6ms/step - loss: nan - mse: nan
Epoch 9/50
2/2 [==============================] - 0s 6ms/step - loss: nan - mse: nan
Epoch 10/50
2/2 [==============================] - 0s 7ms/step - loss: nan - mse: nan
Epoch 11/50
2/2 [==============================] - 0s 5ms/step - loss: nan - mse: nan
Epoch 12/50
2/2 [==============================] - 0s 6ms/step

In [38]:
regression.save("fruit_ann.h5")

In [39]:
from tensorflow.keras.models import load_model
model=load_model('fruit_ann.h5')

In [41]:
ypred = regression.predict(i_test)

In [42]:
ypred

array([[2.3743203e-07],
       [2.4544335e-08],
       [4.3173966e-07],
       [0.0000000e+00],
       [1.2547333e-06],
       [1.3742024e-06],
       [5.0621779e-08],
       [3.5477569e-07],
       [4.7215977e-08],
       [3.4400310e-07],
       [1.8973557e-07],
       [1.0779197e-06]], dtype=float32)

In [43]:
ypred = ypred >0.5
ypred

array([[False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False]])

In [44]:
o_test

array([], shape=(12, 0), dtype=float64)

In [45]:
dataset.head(2)

fruit_label fruit_name fruit_subtype  mass  width  height  color_score
0            1      apple  granny_smith   192    8.4     7.3         0.55
1            1      apple  granny_smith   180    8.0     6.8         0.59

In [49]:
ypred=regression.predict(s.transform(ct.transform([[2,'orange','mandarin',132, 5.6,5.8,0.58]])))

In [50]:
ypred

array([[0.]], dtype=float32)

In [53]:
import pickle
pickle.dump(sc,open('fruit.save','wb'))